version: '3.5'

services:
  ldap-server:
    image: kwart/ldap-server:2017-09-04
    volumes:
      - './resources/ldap/:/mnt/'
    entrypoint:
      - 'java'
      - '-jar'
      - 'ldap-server.jar'
      - '/mnt/users.ldif'
    ports:
      - 10389:10389

  postgres-db:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: users
    volumes:
      - './resources/sql/:/docker-entrypoint-initdb.d/'
    ports: 
      - 5432:5432