version: '3.5'

services:
  ldap-server:
  image: kwart/ldap-server:2017-09-04
  volumes:
    - './resources/:/mnt/'
  entrypoint:
    - 'java'
    - '-jar'
    - 'ldap-server.jar'
    - '/mnt/users.ldif'
  ports:
    - 10389:10389